name: Haiku Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - haiku-support

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests_on_haiku:
    name: Tests on Haiku
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        optimization: ["", "-O2", "-O3"]

    steps:
      - uses: actions/checkout@v4

      - name: Test on Haiku
        uses: cross-platform-actions/action@v1.2.0
        with:
          operating_system: haiku
          version: r1beta5
          architecture: x86-64
          shell: sh
          run: |
            export OPT_CFLAGS="${{ matrix.optimization }}"
            cd test && make check
